INSERT INTO author_review (user_id, author_id, rating, content, created_at, updated_at)
VALUES (1, 165, 5, 'Niesamowity autor, jego książki zmieniły moje podejście do programowania.', now(), NULL),
       (2, 165, 4.5, 'Bardzo wartościowe treści, czasami jednak zbyt rozwlekłe.', now(), NULL),
       (3, 165, 4, 'Dobre praktyki wyjaśnione jasno i przejrzyście.', now(), NULL),
       (4, 165, 3.5, 'Niektóre przykłady już się zestarzały, ale wciąż przydatne.', now(), NULL),
       (5, 165, 5, 'Legenda w świecie programowania, polecam każdemu.', now(), NULL),
       (6, 165, 4, 'Praktyczne rady, które naprawdę działają w codziennej pracy.', now(), NULL),
       (7, 165, 3, 'Treści wartościowe, ale czasami trudne do przyswojenia.', now(), NULL),
       (8, 165, 4.5, 'Bardzo inspirujące podejście do czystego kodu.', now(), NULL),
       (9, 165, 5, 'Najlepszy autor książek programistycznych jakiego znam.', now(), NULL),
       (10, 165, 2.5, 'Trochę zbyt teoretyczne, brakowało mi praktycznych przykładów.', now(), NULL),
       (11, 165, 3.5, 'Dobry autor, ale styl pisania nie dla każdego.', now(), NULL),
       (12, 165, 4, 'Wartościowe książki, choć nie wszystkie równe poziomem.', now(), NULL),
       (13, 165, 5, 'Ikona inżynierii oprogramowania, ogromna wiedza.', now(), NULL),
       (14, 165, 4.5, 'Jego podejście do zasad SOLID to podstawa dla każdego programisty.', now(), NULL),
       (15, 165, 4, 'Mocna treść, choć momentami trudny język.', now(), NULL),
       (16, 165, 3.5, 'Cenne spostrzeżenia, lecz nieco przestarzałe przykłady.', now(), NULL),
       (17, 165, 5, 'Wielki autorytet w branży IT.', now(), NULL),
       (18, 165, 2, 'Niektóre książki zbyt skomplikowane dla początkujących.', now(), NULL),
       (19, 165, 4, 'Dobry balans między teorią a praktyką.', now(), NULL),
       (20, 165, 3, 'Nie wszystko dla mnie było użyteczne.', now(), NULL),
       (21, 165, 4.5, 'Świetne wskazówki dla architektów oprogramowania.', now(), NULL),
       (22, 165, 5, 'Jego książki powinny być obowiązkowe na studiach.', now(), NULL),
       (23, 165, 3.5, 'Dobre, ale czasem zbyt powtarzalne.', now(), NULL),
       (24, 165, 4, 'Rzetelny autor z ogromnym doświadczeniem.', now(), NULL),
       (25, 165, 5, 'Czysty kod to klasyka gatunku, niezbędna w biblioteczce.', now(), NULL),
       (26, 165, 4, 'Książki, do których warto wracać.', now(), NULL),
       (27, 165, 3, 'Trochę trudne do czytania, ale wartościowe.', now(), NULL),
       (28, 165, 4.5, 'Świetnie tłumaczy złożone koncepcje.', now(), NULL),
       (29, 165, 5, 'Dzięki niemu lepiej rozumiem zasady projektowania.', now(), NULL),
       (30, 165, 2.5, 'Niektóre fragmenty niezrozumiałe bez praktyki.', now(), NULL),
       (31, 165, 3.5, 'Ogólnie dobre książki, ale nie każda trafiła w mój gust.', now(), NULL),
       (32, 165, 4, 'Pomógł mi uporządkować wiedzę programistyczną.', now(), NULL),
       (33, 165, 5, 'Mistrz w dziedzinie inżynierii oprogramowania.', now(), NULL),
       (34, 165, 4.5, 'Każda książka niesie ważne przesłanie.', now(), NULL),
       (35, 165, 4, 'Bardzo praktyczne podejście do programowania.', now(), NULL),
       (36, 165, 3, 'Momentami zbyt trudne dla mniej zaawansowanych.', now(), NULL),
       (37, 165, 4.5, 'Ogromna wiedza, świetnie przekazana.', now(), NULL),
       (38, 165, 5, 'Autor, który wywarł ogromny wpływ na branżę IT.', now(), NULL),
       (39, 165, 3.5, 'Dobre, ale nie zawsze lekkie w odbiorze.', now(), NULL),
       (40, 165, 4, 'Solidne fundamenty programowania.', now(), NULL),
       (41, 165, 5, 'Bez niego świat IT wyglądałby inaczej.', now(), NULL),
       (42, 165, 2.5, 'Niektóre książki mało przystępne.', now(), NULL),
       (43, 165, 3.5, 'Trochę przestarzałe, ale nadal użyteczne.', now(), NULL),
       (44, 165, 4, 'Wiele praktycznych przykładów.', now(), NULL),
       (45, 165, 5, 'Klasyka, którą zna każdy programista.', now(), NULL),
       (46, 165, 4, 'Bardzo dobra jakość treści.', now(), NULL),
       (47, 165, 3, 'Nie wszystko przypadło mi do gustu.', now(), NULL),
       (48, 165, 4.5, 'Inspirujący autor.', now(), NULL),
       (49, 165, 5, 'Czysty kod to biblia programistów.', now(), NULL),
       (50, 165, 4, 'Polecam wszystkim, którzy chcą pisać lepszy kod.', now(), NULL);


INSERT INTO author_review (user_id, author_id, rating, content, created_at, updated_at)
VALUES (1, 164, 5, 'Harry Potter to moja ulubiona seria, magiczny świat na zawsze w moim sercu.', now(), NULL),
       (2, 164, 4.5, 'Fantastyczna wyobraźnia, świetne postaci, choć ostatnie tomy mogły być krótsze.', now(), NULL),
       (3, 164, 4, 'Bardzo dobra literatura młodzieżowa, pełna przygód.', now(), NULL),
       (4, 164, 3.5, 'Dobre książki, choć nie wszystkie utrzymują ten sam poziom.', now(), NULL),
       (5, 164, 5, 'Autorka, która wychowała całe pokolenie czytelników.', now(), NULL),
       (6, 164, 4, 'Świetnie napisane, dobrze się czyta niezależnie od wieku.', now(), NULL),
       (7, 164, 3, 'Nie wszystkie tomy mnie porwały, ale ogólnie pozytywnie.', now(), NULL),
       (8, 164, 4.5, 'Magiczna seria, pełna emocji i wciągającej fabuły.', now(), NULL),
       (9, 164, 5, 'Najlepsza seria książek młodzieżowych jaką czytałem.', now(), NULL),
       (10, 164, 2.5, 'Nie mój klimat, choć rozumiem fenomen.', now(), NULL),
       (11, 164, 3.5, 'Przyjemna lektura, ale trochę przereklamowana.', now(), NULL),
       (12, 164, 4, 'Wciągająca opowieść, którą łatwo pokochać.', now(), NULL),
       (13, 164, 5, 'Harry Potter to klasyka, do której często wracam.', now(), NULL),
       (14, 164, 4.5, 'Cudownie wykreowany świat, pełen magii i przygód.', now(), NULL),
       (15, 164, 4, 'Dobra autorka, świetne książki dla młodych czytelników.', now(), NULL),
       (16, 164, 3.5, 'Momentami przewidywalne, ale wciąż wciągające.', now(), NULL),
       (17, 164, 5, 'J.K. Rowling to geniusz literatury młodzieżowej.', now(), NULL),
       (18, 164, 2, 'Nie przepadam za tą serią, zbyt dziecinna.', now(), NULL),
       (19, 164, 4, 'Wciągająca historia, warta przeczytania.', now(), NULL),
       (20, 164, 3, 'Nie wszystkie wątki mnie przekonały.', now(), NULL),
       (21, 164, 4.5, 'Cudowna seria, świetnie rozwijające się postacie.', now(), NULL),
       (22, 164, 5, 'Książki mojego dzieciństwa, kocham je całym sercem.', now(), NULL),
       (23, 164, 3.5, 'Niektóre fragmenty dłużyły się, ale i tak warto.', now(), NULL),
       (24, 164, 4, 'Ciekawe postaci i wciągająca fabuła.', now(), NULL),
       (25, 164, 5, 'Najlepsza seria fantasy dla młodzieży.', now(), NULL),
       (26, 164, 4, 'Dobre książki, które inspirują młodych ludzi.', now(), NULL),
       (27, 164, 3, 'Nie każda część była równie ciekawa.', now(), NULL),
       (28, 164, 4.5, 'Świetnie napisana seria, pełna emocji.', now(), NULL),
       (29, 164, 5, 'Cudowna przygoda od pierwszej do ostatniej części.', now(), NULL),
       (30, 164, 2.5, 'Nie rozumiem fenomenu, ale widać talent autorki.', now(), NULL),
       (31, 164, 3.5, 'Dobre, ale nie aż tak wyjątkowe jak się mówi.', now(), NULL),
       (32, 164, 4, 'Seria, która wciągnęła mnie bez reszty.', now(), NULL),
       (33, 164, 5, 'Magiczny świat, w którym można się zatracić.', now(), NULL),
       (34, 164, 4.5, 'Uwielbiam klimat Hogwartu i bohaterów.', now(), NULL),
       (35, 164, 4, 'Solidna literatura młodzieżowa.', now(), NULL),
       (36, 164, 3, 'Nie wszystkie tomy były równe jakościowo.', now(), NULL),
       (37, 164, 4.5, 'Pełna magii, przyjaźni i emocji seria.', now(), NULL),
       (38, 164, 5, 'Bez wątpienia najlepsza autorka fantasy młodzieżowego.', now(), NULL),
       (39, 164, 3.5, 'Niektóre wątki były powtarzalne.', now(), NULL),
       (40, 164, 4, 'Bardzo dobrze napisana saga.', now(), NULL),
       (41, 164, 5, 'Harry Potter zmienił moje życie czytelnicze.', now(), NULL),
       (42, 164, 2.5, 'Nie do końca mój styl, ale szanuję.', now(), NULL),
       (43, 164, 3.5, 'Seria ma swoje plusy i minusy.', now(), NULL),
       (44, 164, 4, 'Zasłużony fenomen literacki.', now(), NULL),
       (45, 164, 5, 'Najlepsze książki mojego dzieciństwa.', now(), NULL),
       (46, 164, 4, 'Wciągająca i dobrze napisana historia.', now(), NULL),
       (47, 164, 3, 'Część książek była moim zdaniem zbyt rozwleczona.', now(), NULL),
       (48, 164, 4.5, 'Klimatyczna i pełna emocji saga.', now(), NULL),
       (49, 164, 5, 'Uwielbiam Harry’ego Pottera, to klasyka gatunku.', now(), NULL),
       (50, 164, 4, 'Świetna seria, polecam każdemu.', now(), NULL);


INSERT INTO author_review (user_id, author_id, rating, content, created_at, updated_at)
VALUES (1, 162, 4, 'Dynamiczne thrillery, które szybko się czyta.', now(), NULL),
       (2, 162, 3.5, 'Produkuje książki w błyskawicznym tempie, różny poziom, ale ogólnie dobre.', now(), NULL),
       (3, 162, 4.5, 'Świetne pomysły, zwłaszcza w seriach prawniczych.', now(), NULL),
       (4, 162, 3, 'Trochę nierówne – jedne książki super, inne przeciętne.', now(), NULL),
       (5, 162, 5, 'Mój ulubiony polski autor współczesny.', now(), NULL),
       (6, 162, 4, 'Dobre tempo akcji, lekkie pióro.', now(), NULL),
       (7, 162, 3.5, 'Czasami przesadza z ilością wątków.', now(), NULL),
       (8, 162, 4.5, 'Fenomenalne serie, wciągają jak mało co.', now(), NULL),
       (9, 162, 5, 'Uwielbiam jego styl i bohaterów.', now(), NULL),
       (10, 162, 2.5, 'Za dużo książek, czasem kosztem jakości.', now(), NULL),
       (11, 162, 3, 'Nie zawsze trafia w mój gust.', now(), NULL),
       (12, 162, 4, 'Potrafi świetnie zbudować napięcie.', now(), NULL),
       (13, 162, 5, 'Każdą jego nowość kupuję w dniu premiery.', now(), NULL),
       (14, 162, 4.5, 'Jedna z najlepszych serii kryminalnych w Polsce.', now(), NULL),
       (15, 162, 4, 'Świetny warsztat i dobre dialogi.', now(), NULL),
       (16, 162, 3.5, 'Trochę przewidywalne wątki.', now(), NULL),
       (17, 162, 5, 'Genialny twórca literatury popularnej.', now(), NULL),
       (18, 162, 2, 'Nie mój klimat, wolę inne gatunki.', now(), NULL),
       (19, 162, 4, 'Zawsze dynamiczna akcja i ciekawi bohaterowie.', now(), NULL),
       (20, 162, 3, 'Bywa schematyczny.', now(), NULL),
       (21, 162, 4.5, 'Uwielbiam jego pomysłowość i tempo.', now(), NULL),
       (22, 162, 5, 'Najlepszy polski autor kryminałów.', now(), NULL),
       (23, 162, 3.5, 'Niektóre zakończenia są zbyt szybkie.', now(), NULL),
       (24, 162, 4, 'Ciekawe fabuły i wartka akcja.', now(), NULL),
       (25, 162, 5, 'Wciągająca proza, którą się pochłania.', now(), NULL),
       (26, 162, 4, 'Świetne postacie kobiece.', now(), NULL),
       (27, 162, 3, 'Zdarzają się słabsze tomy.', now(), NULL),
       (28, 162, 4.5, 'Cenię za ogromną pracowitość i pasję.', now(), NULL),
       (29, 162, 5, 'Rewelacyjne książki, polecam każdemu.', now(), NULL),
       (30, 162, 2.5, 'Pisze za dużo, nie wszystko na wysokim poziomie.', now(), NULL),
       (31, 162, 3.5, 'Część serii interesująca, część przeciętna.', now(), NULL),
       (32, 162, 4, 'Fajny język i ciekawe dialogi.', now(), NULL),
       (33, 162, 5, 'Czytam wszystko od Mroza, uwielbiam!', now(), NULL),
       (34, 162, 4.5, 'Dobre thrillery i kryminały.', now(), NULL),
       (35, 162, 4, 'Solidny warsztat i dobra narracja.', now(), NULL),
       (36, 162, 3, 'Nie wszystko mi odpowiada.', now(), NULL),
       (37, 162, 4.5, 'Potrafi mocno zaskoczyć fabułą.', now(), NULL),
       (38, 162, 5, 'Bezkonkurencyjny w polskiej literaturze popularnej.', now(), NULL),
       (39, 162, 3.5, 'Bywa, że powtarza schematy.', now(), NULL),
       (40, 162, 4, 'Dobrze się czyta w podróży.', now(), NULL),
       (41, 162, 5, 'Jeden z najlepszych polskich pisarzy.', now(), NULL),
       (42, 162, 2.5, 'Dla mnie zbyt lekka literatura.', now(), NULL),
       (43, 162, 3.5, 'Nierówna jakość poszczególnych tomów.', now(), NULL),
       (44, 162, 4, 'Wciągające fabuły i szybkie tempo.', now(), NULL),
       (45, 162, 5, 'Uwielbiam jego książki – czytam wszystkie.', now(), NULL),
       (46, 162, 4, 'Dobry w kreowaniu bohaterów.', now(), NULL),
       (47, 162, 3, 'Nie wszystko do mnie trafia.', now(), NULL),
       (48, 162, 4.5, 'Zawsze trzyma w napięciu.', now(), NULL),
       (49, 162, 5, 'Fenomenalny autor, wart każdej nagrody.', now(), NULL),
       (50, 162, 4, 'Świetny przedstawiciel polskiego kryminału.', now(), NULL);


INSERT INTO author_review (user_id, author_id, rating, content, created_at, updated_at)
VALUES (1, 163, 5, 'Arcydzieło literatury fantasy.', now(), NULL),
       (2, 163, 4.5, 'Jego światotwórstwo jest niesamowite.', now(), NULL),
       (3, 163, 5, 'Władca Pierścieni to klasyk wszech czasów.', now(), NULL),
       (4, 163, 4, 'Hobbit to piękna opowieść, choć wolę sagę.', now(), NULL),
       (5, 163, 5, 'Mistrz języka i epickich opowieści.', now(), NULL),
       (6, 163, 4.5, 'Świetnie wykreowany świat Śródziemia.', now(), NULL),
       (7, 163, 5, 'Każda książka to przygoda na całe życie.', now(), NULL),
       (8, 163, 4, 'Momentami trudniejszy język, ale warto.', now(), NULL),
       (9, 163, 5, 'Najlepsza fantasy w historii.', now(), NULL),
       (10, 163, 4.5, 'Czytam go od lat i zawsze zachwyca.', now(), NULL),
       (11, 163, 5, 'Absolutna legenda literatury.', now(), NULL),
       (12, 163, 5, 'Śródziemie nigdy nie przestaje fascynować.', now(), NULL),
       (13, 163, 4.5, 'Genialny twórca całego gatunku fantasy.', now(), NULL),
       (14, 163, 5, 'Ulubiony autor mojego dzieciństwa.', now(), NULL),
       (15, 163, 5, 'Arcydzieła, które przetrwają wieki.', now(), NULL),
       (16, 163, 4, 'Momentami rozwlekłe opisy.', now(), NULL),
       (17, 163, 5, 'Dzięki niemu pokochałem literaturę.', now(), NULL),
       (18, 163, 5, 'Wspaniały język i narracja.', now(), NULL),
       (19, 163, 4.5, 'Każde zdanie buduje klimat.', now(), NULL),
       (20, 163, 5, 'Nie ma lepszego autora fantasy.', now(), NULL),
       (21, 163, 5, 'Legenda światowej literatury.', now(), NULL),
       (22, 163, 4, 'Hobbit trochę bardziej bajkowy.', now(), NULL),
       (23, 163, 5, 'Prawdziwy ojciec współczesnej fantasy.', now(), NULL),
       (24, 163, 4.5, 'Uwielbiam bogactwo opisów.', now(), NULL),
       (25, 163, 5, 'Książki, do których zawsze wracam.', now(), NULL),
       (26, 163, 5, 'Władca Pierścieni to moja Biblia fantasy.', now(), NULL),
       (27, 163, 4.5, 'Przepiękny styl pisania.', now(), NULL),
       (28, 163, 5, 'Niepowtarzalny klimat.', now(), NULL),
       (29, 163, 5, 'Wielki mistrz literatury.', now(), NULL),
       (30, 163, 4, 'Trzeba mieć cierpliwość do jego stylu.', now(), NULL),
       (31, 163, 5, 'Każda książka to podróż.', now(), NULL),
       (32, 163, 5, 'Śródziemie żyje we mnie od dziecka.', now(), NULL),
       (33, 163, 5, 'Tolkien to absolutny numer jeden.', now(), NULL),
       (34, 163, 4.5, 'Bardzo wymagający, ale nagradzający.', now(), NULL),
       (35, 163, 5, 'Twórca fundamentów fantasy.', now(), NULL),
       (36, 163, 5, 'Genialny językoznawca i pisarz.', now(), NULL),
       (37, 163, 4, 'Długie fragmenty mogą nużyć.', now(), NULL),
       (38, 163, 5, 'Nie do podrobienia styl.', now(), NULL),
       (39, 163, 5, 'Tolkien to legenda.', now(), NULL),
       (40, 163, 4.5, 'Jedyny w swoim rodzaju.', now(), NULL),
       (41, 163, 5, 'Arcymistrz pióra.', now(), NULL),
       (42, 163, 5, 'Wszystkie książki genialne.', now(), NULL),
       (43, 163, 4.5, 'Hobbit to cudowna lektura.', now(), NULL),
       (44, 163, 5, 'Władca Pierścieni – ponadczasowy.', now(), NULL),
       (45, 163, 5, 'Tolkien to fundament fantastyki.', now(), NULL),
       (46, 163, 5, 'Uwielbiam każdy jego tekst.', now(), NULL),
       (47, 163, 4.5, 'Wciągający świat Śródziemia.', now(), NULL),
       (48, 163, 5, 'Mój ulubiony autor wszechczasów.', now(), NULL),
       (49, 163, 5, 'Nieśmiertelny klasyk.', now(), NULL),
       (50, 163, 5, 'Jego książki są wieczne.', now(), NULL);


INSERT INTO author_review (user_id, author_id, rating, content, created_at, updated_at)
VALUES (1, 161, 5, 'Mistrz horroru, nie ma sobie równych.', now(), NULL),
       (2, 161, 4.5, 'Uwielbiam jego wyobraźnię.', now(), NULL),
       (3, 161, 5, 'Lśnienie to arcydzieło grozy.', now(), NULL),
       (4, 161, 4, 'Bardzo dużo pisze, czasem mniej udane.', now(), NULL),
       (5, 161, 5, 'Najlepszy twórca horrorów.', now(), NULL),
       (6, 161, 4.5, 'Potrafi genialnie budować klimat.', now(), NULL),
       (7, 161, 5, 'Carrie i To to moje ulubione powieści.', now(), NULL),
       (8, 161, 4, 'Niektóre książki trochę za długie.', now(), NULL),
       (9, 161, 5, 'Absolutna legenda literatury grozy.', now(), NULL),
       (10, 161, 4.5, 'Bardzo plastyczny język i opisy.', now(), NULL),
       (11, 161, 5, 'Prawdziwy mistrz opowieści.', now(), NULL),
       (12, 161, 5, 'Jego styl jest niepowtarzalny.', now(), NULL),
       (13, 161, 4.5, 'Świetny storyteller.', now(), NULL),
       (14, 161, 5, 'Czytam go od lat i się nie nudzi.', now(), NULL),
       (15, 161, 5, 'Numer jeden w literaturze grozy.', now(), NULL),
       (16, 161, 4, 'Nie wszystkie książki tak samo dobre.', now(), NULL),
       (17, 161, 5, 'Jego powieści wciągają bez reszty.', now(), NULL),
       (18, 161, 5, 'Genialny pomysłowy autor.', now(), NULL),
       (19, 161, 4.5, 'Każdy horror to arcydzieło.', now(), NULL),
       (20, 161, 5, 'Najlepszy pisarz współczesny.', now(), NULL),
       (21, 161, 5, 'Kocham jego opowieści.', now(), NULL),
       (22, 161, 4, 'Niektóre zakończenia rozczarowują.', now(), NULL),
       (23, 161, 5, 'Król horroru.', now(), NULL),
       (24, 161, 4.5, 'Świetny w budowaniu napięcia.', now(), NULL),
       (25, 161, 5, 'Nie ma drugiego takiego autora.', now(), NULL),
       (26, 161, 5, 'Najbardziej twórczy pisarz.', now(), NULL),
       (27, 161, 4.5, 'Dobre nawet krótkie formy.', now(), NULL),
       (28, 161, 5, 'Klasa sama w sobie.', now(), NULL),
       (29, 161, 5, 'Fenomen literatury grozy.', now(), NULL),
       (30, 161, 4, 'Czasami przesadnie rozwlekły.', now(), NULL),
       (31, 161, 5, 'Lśnienie czy To to absolutne perełki.', now(), NULL),
       (32, 161, 5, 'Niepowtarzalna wyobraźnia.', now(), NULL),
       (33, 161, 5, 'King to mistrz nastroju.', now(), NULL),
       (34, 161, 4.5, 'Kapitalne postacie.', now(), NULL),
       (35, 161, 5, 'Najlepsze horrory ever.', now(), NULL),
       (36, 161, 5, 'Klimatyczne i straszne.', now(), NULL),
       (37, 161, 4, 'Niektóre książki za długie.', now(), NULL),
       (38, 161, 5, 'Pisarz totalny.', now(), NULL),
       (39, 161, 5, 'King = horror.', now(), NULL),
       (40, 161, 4.5, 'Świetne adaptacje filmowe.', now(), NULL),
       (41, 161, 5, 'Mój ulubiony autor.', now(), NULL),
       (42, 161, 5, 'Czytam każdą jego książkę.', now(), NULL),
       (43, 161, 4.5, 'Mistrz grozy i klimatu.', now(), NULL),
       (44, 161, 5, 'Nie do zastąpienia w literaturze.', now(), NULL),
       (45, 161, 5, 'King to klasa sama w sobie.', now(), NULL),
       (46, 161, 5, 'Uwielbiam jego horrory.', now(), NULL),
       (47, 161, 4.5, 'Niezwykle kreatywny autor.', now(), NULL),
       (48, 161, 5, 'Król literatury.', now(), NULL),
       (49, 161, 5, 'Stephen King to legenda.', now(), NULL),
       (50, 161, 5, 'Najbardziej kultowy autor grozy.', now(), NULL);


update author as a
set total_reviews  = (select count(*) from author_review ar where ar.author_id = a.id),
    average_rating = (select avg(ar.rating) from author_review ar where ar.author_id = a.id)