INSERT INTO challenge (user_id, genre_id, title, description, start_at, end_at, type, goal_value, total_participants,
                       created_at, updated_at)
VALUES (1, NULL, '100 książek w 30 dni', 'Wyzwanie polega na przeczytaniu 100 książek w jeden miesiąc.',
        now() - interval '15 days', now() + interval '15 days', 'BOOK_COUNT', 100, 15, now(), NULL),
       (2, NULL, '10 000 stron w 2 miesiące', 'Celem jest przeczytanie 10 000 stron w dwa miesiące.',
        now() - interval '20 days', now() + interval '40 days', 'PAGE_COUNT', 10000, 15, now(), NULL),
       (3, 1, '20 książek fantasy', 'Przeczytaj 20 książek fantasy w ciągu trzech miesięcy.',
        now() - interval '10 days', now() + interval '80 days', 'GENRE_BOOKS', 20, 15, now(), NULL),
       (4, NULL, '15 autorów w rok', 'Przeczytaj książki co najmniej 15 różnych autorów w ciągu roku.',
        now() - interval '100 days', now() + interval '265 days', 'AUTHOR_COUNT', 15, 15, now(), NULL),
       (5, NULL, '5 gatunków w pół roku', 'Spróbuj przeczytać książki z 5 różnych gatunków.',
        now() - interval '30 days', now() + interval '150 days', 'GENRE_COUNT', 5, 15, now(), NULL),
       (6, NULL, '50 książek w 6 miesięcy', 'Celem jest przeczytanie 50 książek w pół roku.',
        now() - interval '200 days', now() - interval '10 days', 'BOOK_COUNT', 50, 15, now(), NULL),
       (7, NULL, '3000 stron w miesiąc', 'Przeczytaj 3000 stron w 30 dni.', now() - interval '5 days',
        now() + interval '25 days', 'PAGE_COUNT', 3000, 15, now(), NULL),
       (8, 2, '10 książek kryminalnych', 'Wyzwanie polega na przeczytaniu 10 książek kryminalnych w 60 dni.',
        now() - interval '40 days', now() - interval '1 day', 'GENRE_BOOKS', 10, 15, now(), NULL),
       (9, NULL, '7 autorów w 3 miesiące', 'Przeczytaj książki 7 różnych autorów.', now() - interval '20 days',
        now() + interval '70 days', 'AUTHOR_COUNT', 7, 15, now(), NULL),
       (10, NULL, '200 książek w rok', 'Wielkie wyzwanie – 200 książek w ciągu jednego roku.',
        now() - interval '50 days', now() + interval '315 days', 'BOOK_COUNT', 200, 15, now(), NULL);


INSERT INTO challenge (user_id, genre_id, title, description, start_at, end_at, type, goal_value, total_participants,
                       created_at, updated_at)
VALUES (1, 1, 'Przeczytaj 50 książek w miesiąc', 'Wyzwanie polega na przeczytaniu 50 książek w 30 dni',
        now() - interval '5 days', now() + interval '25 days', 'BOOK_COUNT', 50, 10, now(), NULL),
       (2, 2, '1000 stron w 15 dni', 'Celem jest przeczytanie 1000 stron w ciągu 15 dni', now() - interval '10 days',
        now() + interval '5 days', 'PAGE_COUNT', 1000, 10, now(), NULL),
       (3, 3, '5 autorów w miesiąc', 'Przeczytaj książki od 5 różnych autorów w miesiąc', now() - interval '20 days',
        now() + interval '10 days', 'AUTHOR_COUNT', 5, 10, now(), NULL),
       (4, 1, '10 książek fantasy', 'Celem jest przeczytanie 10 książek fantasy', now() - interval '3 days',
        now() + interval '27 days', 'GENRE_BOOKS', 10, 10, now(), NULL),
       (5, 4, 'Przeczytaj 20 książek w tydzień', 'Wyzwanie dla bardzo szybkich czytelników', now() - interval '2 days',
        now() + interval '5 days', 'BOOK_COUNT', 20, 10, now(), NULL),
       (6, 2, '50 stron dziennie', 'Przeczytaj codziennie 50 stron przez miesiąc', now() - interval '15 days',
        now() + interval '15 days', 'PAGE_COUNT', 1500, 10, now(), NULL),
       (7, 3, '3 różne gatunki', 'Przeczytaj książki z 3 różnych gatunków', now() - interval '5 days',
        now() + interval '25 days', 'GENRE_COUNT', 3, 10, now(), NULL),
       (8, 1, '30 książek w miesiąc', 'Przeczytaj 30 książek w ciągu miesiąca', now() - interval '10 days',
        now() + interval '20 days', 'BOOK_COUNT', 30, 10, now(), NULL),
       (9, 4, 'Czytaj codziennie 100 stron', 'Codziennie 100 stron przez 15 dni', now() - interval '15 days',
        now() + interval '0 days', 'PAGE_COUNT', 1500, 10, now(), NULL),
       (10, 2, '5 gatunków literackich', 'Przeczytaj książki z 5 różnych gatunków', now() - interval '7 days',
        now() + interval '23 days', 'GENRE_COUNT', 5, 10, now(), NULL);


INSERT INTO challenge (user_id, genre_id, title, description, start_at, end_at, type, goal_value, total_participants,
                       created_at, updated_at)
VALUES (1, 1, 'Przeczytaj 20 książek fantasy w miesiąc', 'Celem jest przeczytanie 20 książek fantasy w ciągu 30 dni.',
        now() - interval '10 days', now() + interval '20 days', 'GENRE_BOOKS', 20, 15, now(), NULL),
       (2, 2, '2000 stron w 30 dni', 'Przeczytaj 2000 stron literatury kryminalnej w ciągu miesiąca.',
        now() - interval '5 days', now() + interval '25 days', 'PAGE_COUNT', 2000, 15, now(), NULL),
       (3, NULL, '10 autorów w miesiąc', 'Przeczytaj książki od 10 różnych autorów w ciągu 30 dni.',
        now() - interval '2 days', now() + interval '28 days', 'AUTHOR_COUNT', 10, 15, now(), NULL),
       (4, 3, '10 książek horroru', 'Przeczytaj 10 książek z gatunku horror w ciągu miesiąca.',
        now() - interval '15 days', now() + interval '15 days', 'GENRE_BOOKS', 10, 15, now(), NULL),
       (5, NULL, 'Przeczytaj 50 książek', 'Celem jest przeczytanie 50 książek w ciągu 2 miesięcy.',
        now() - interval '20 days', now() + interval '40 days', 'BOOK_COUNT', 50, 15, now(), NULL),
       (6, 4, 'Czytanie 1000 stron non-fiction', 'Przeczytaj 1000 stron książek non-fiction w ciągu miesiąca.',
        now() - interval '7 days', now() + interval '23 days', 'PAGE_COUNT', 1000, 15, now(), NULL),
       (7, NULL, 'Przeczytaj 5 autorów klasyki', 'Przeczytaj książki od 5 różnych autorów klasyki literatury.',
        now() - interval '10 days', now() + interval '20 days', 'AUTHOR_COUNT', 5, 15, now(), NULL),
       (8, 1, '15 książek fantasy', 'Celem jest przeczytanie 15 książek fantasy w ciągu miesiąca.',
        now() - interval '3 days', now() + interval '27 days', 'GENRE_BOOKS', 15, 15, now(), NULL),
       (9, 2, '500 stron kryminału', 'Przeczytaj 500 stron literatury kryminalnej w ciągu 10 dni.',
        now() - interval '5 days', now() + interval '5 days', 'PAGE_COUNT', 500, 15, now(), NULL),
       (10, NULL, 'Przeczytaj 7 książek w tydzień', 'Szybkie wyzwanie: 7 książek w 7 dni.', now() - interval '7 days',
        now() + interval '0 days', 'BOOK_COUNT', 7, 15, now(), NULL);
