server:
  servlet:
    context-path: /api
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: WirtualnyRegalBackend
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [correlationId=%X{correlationId}] [userId=%X{userId:-anonymous}] %-5level %logger{36} - %msg%n"

app:
  protocol: http
  host: localhost
  security:
    jwt:
      secret-key: b21a483517257c7ac0eb20b47a6fd8e6bdba832b7393edcdd73364d379eb7ad8
      expiration-days: 3
    excluded-paths:
      - "/v1/auth/**"
      - "/v1/book-covers/**"
      - "/v1/user-profile-pictures/**"
      - "/v1/author-profile-pictures/**"
  book-cover:
    url-prefix: /api/v1/book-covers/
  user-profile-picture:
    url-prefix: /api/v1/user-profile-pictures/
  author-profile-picture:
    url-prefix: /api/v1/author-profile-pictures/
  review:
    valid-ratings: [ 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5 ]