server:
  servlet:
    context-path: /api
  port: 8080
  address: localhost

spring:
  application:
    name: WirtualnyRegalBackend

  datasource:
    url: jdbc:postgresql://localhost:5433/VirtualBookshelf
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [correlationId=%X{correlationId}] [userId=%X{userId:-anonymous}] %-5level %logger{36} - %msg%n"
  level:
    org.hl.wirtualnyregalbackend: TRACE
    org.springframework.boot.context.config: TRACE

jwt:
  secret-key: b21a483517257c7ac0eb20b47a6fd8e6bdba832b7393edcdd73364d379eb7ad8
  expiration-days: 3

app:
  protocol: http
